FROM python:3.8.13 as base

ENV PYTHONPATH=$PYTHONPATH:/src/

COPY ./requirements.txt /src/requirements.txt

WORKDIR /src

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./ /src/

CMD ["python", "populate_db.py"]


# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script
